# -*- mode: yaml -*-
# vi: set ft=yaml :

verbose_salt_output: false
run_highstate_on_up: true
salt_versiono: "2019.02"

hosts:
  minecraft:
    cpu: 4
    ram: 8000
    ip: 172.28.128.10
    # Size in GB - used only for creating storage disk.
    # Disk will be dynamically allocated (thin provisioned).
    storage: 200
    portmap:
      - guest: 25565
        host: 20202
      - guest: 8123
        host: 20203
      - guest: 80
        host: 80
      - guest: 443
        host: 443
